version: '3.5'

volumes:
  WordPress:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/mel-harc/Desktop/inception/wordpress
  DB:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/mel-harc/Desktop/inception/srcs/mariadb

networks:
  NT:

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    networks:
      - NT
    volumes:
      - DB:/var/lib/msql
    env_file:
      - .env

  wordpress:
    image: wordpress
    build: ./requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - NT
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    depends_on:
      - wordpress
    networks:
      - NT
    ports:
      - "443:443"
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
